name: ooniengine
description: dart binding for OONI Engine
version: 0.1.0
homepage: https://github.com/ooni/probe-cli
documentation: https://github.com/ooni/probe-cli
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.2.0
  ffigen: ^6.0.1
  json_serializable: ^6.3.1

ffigen:
  output: 'lib/bindings.dart'
  name: 'OONIEngineFFI'
  headers:
    entry-points:
      - '../../pkg/ooniengine/engine.h'
